/* ── CASOS NUEVOS ────────────────────────────────────────────────
   Sustituyen al caso que repetía el «caso a fondo» de la capa
   profesional: así cada ficha tiene el caso a fondo + 3 casos distintos. */
(function(){
var N = {
 ridge:[0,["","Retail","Previsión de afluencia a tiendas con decenas de indicadores locales correlacionados (paro, renta, población).","Ridge usa todos los indicadores sin que uno domine por casualidad.","Previsión estable al abrir tiendas en barrios nuevos."]],
 lasso:[0,["","Educación","¿Qué 5 de las 70 preguntas de la encuesta de alumnos predicen el abandono?","Lasso deja a cero las preguntas que no aportan.","Encuesta de seguimiento de 5 preguntas en lugar de 70."]],
 elastic:[0,["","Agricultura de precisión","Predecir la cosecha con cientos de bandas de satélite muy correlacionadas.","Selecciona bloques de bandas útiles sin quedarse con una al azar.","Previsión de cosecha por parcela con un modelo estable año a año."]],
 poisson:[0,["","Mantenimiento","Número de averías al mes por ascensor según antigüedad, uso y fabricante.","Tasa de averías esperada por equipo con efectos multiplicativos legibles.","Plan de revisiones priorizando los ascensores con más averías esperadas."]],
 quantile:[0,["","Tesorería","¿Cuánto efectivo puede salir en el peor día razonable del mes?","P99 de salidas de caja según calendario y estacionalidad.","Colchón de liquidez dimensionado al riesgo real."]],
 bayesridge:[0,["","Bodegas","Estimar la calidad de una añada nueva con muy pocas catas.","Predicción con intervalo que se estrecha con cada cata nueva.","Decidir el precio de salida sabiendo cuánta incertidumbre queda."]],
 gp:[0,["","Cosmética","Encontrar la mezcla de 5 ingredientes que maximiza la estabilidad de una crema.","El GP propone la siguiente fórmula a probar donde más se aprende.","Fórmula óptima con la mitad de lotes de prueba."]],
 svr:[0,["","Construcción","Resistencia del hormigón a 28 días según la mezcla, con pocas probetas.","Regresión no lineal robusta que ignora el ruido pequeño de laboratorio.","Ajustar la dosificación sin esperar al ensayo completo."]],
 gbr:[0,["","Movilidad","Estimar la duración de un trayecto en taxi o VTC antes de aceptarlo.","Aprende interacciones entre hora, zona, lluvia y eventos.","Precio cerrado al cliente con menos desviaciones."]],
 arbol:[0,["","Triaje","Reglas sencillas para priorizar pacientes en urgencias.","Un árbol poco profundo convierte el histórico en un protocolo legible.","Protocolo de triaje que el personal puede aplicar sin ordenador."]],
 rf:[0,["","Seguros de hogar","Probabilidad de siniestro por vivienda con datos de catastro, clima y póliza.","Combina variables muy distintas sin preprocesado y con importancia por permutación.","Tarifa por vivienda y no por código postal."]],
 extratrees:[0,["","Medio ambiente","Clasificar el uso del suelo con imágenes de satélite actualizadas cada semana.","Reentrena rápido con millones de píxeles etiquetados.","Mapas de deforestación casi en tiempo real."]],
 xgboost:[0,["","Logística","¿Llegará tarde este pedido? Se decide al preparar el envío.","Probabilidad de retraso con transportista, ruta, peso y día.","Avisar al cliente antes o cambiar de transportista."]],
 lightgbm:[0,["","Apuestas deportivas","Probabilidad de cada resultado con miles de variables por partido.","Reentrena en minutos tras cada jornada.","Cuotas ajustadas antes que la competencia."]],
 catboost:[0,["","Hoteles","Probabilidad de no presentarse (no-show) con país, agencia y tipo de tarifa.","Categorías de alta cardinalidad sin encoding manual.","Overbooking controlado por tipo de reserva."]],
 adaboost:[0,["","Correo corporativo","Filtro de phishing ligero en un servidor antiguo.","Combinación de reglas débiles (dominio, enlaces, urgencia) en un clasificador fuerte.","Bloqueo de correos sospechosos sin hardware nuevo."]],
 svmlin:[0,["","Administración pública","Clasificar solicitudes ciudadanas por departamento a partir del texto.","SVM lineal sobre TF-IDF: preciso y barato con mucho vocabulario.","Respuesta más rápida al ciudadano."]],
 svmker:[0,["","Agroalimentación","Separar fruta apta y no apta por color y firmeza, con frontera curva.","Kernel RBF que dibuja la región de fruta apta.","Clasificadora automática de fruta con menos desperdicio."]],
 knn:[0,["","Salud","Pacientes parecidos al actual y cómo evolucionaron.","Los K pacientes más similares (por historia y pruebas) se muestran al médico.","Apoyo a la decisión basado en casos reales, no en una caja negra."]],
 nb:[0,["","Marketplace","Detectar anuncios fraudulentos por su texto.","Palabras típicas de fraude («transferencia», «urgente») suman evidencia.","Revisión manual solo de anuncios con alta probabilidad."]],
 lda:[0,["","Riesgo de empresas","Separar empresas sanas de empresas en dificultades con ratios financieros (al estilo del Z-score).","Una combinación lineal de ratios que discrimina y se puede explicar.","Semáforo de riesgo de clientes empresa."]],
 qda:[0,["","Ciberseguridad","Distinguir tráfico normal (muy regular) de tráfico de bots (muy disperso).","Frontera curva que respeta la distinta dispersión de cada grupo.","Bloqueo de bots con pocos falsos positivos."]],
 cox:[0,["","Energía","¿Cuándo dejará un cliente de la comercializadora tras subir la tarifa?","Curvas de supervivencia antes y después de la subida, con los aún activos como censurados.","Momento óptimo para ofrecer la renovación."]],
 uplift:[0,["","Banca","¿A quién le hace cambiar una llamada para contratar un fondo?","Uplift estimado con un piloto aleatorizado de llamadas.","Llamar solo a quien cambia de decisión: menos llamadas, más contratos."]],
 propensity:[0,["","Producto digital","¿Aumentó el uso de la app la nueva función que solo activaron algunos usuarios?","Emparejamiento por propensión entre quienes la activaron y «gemelos» que no.","Decidir si la función merece activarse para todos."]],
 mlp:[0,["","Industria","Predecir la calidad final de un producto a partir de 40 parámetros de proceso que interactúan.","La red aprende interacciones complejas entre parámetros.","Ajustes de proceso antes de que salga el lote defectuoso."]],
 cnn:[0,["","Salud","Priorizar radiografías de tórax con hallazgos para el radiólogo.","CNN preentrenada que puntúa cada imagen.","Las urgentes se leen primero; el diagnóstico final sigue siendo humano."]],
 rnn:[0,["","Producto","Autocompletar en el buscador de una tienda online.","Modelo secuencial que predice la siguiente palabra según lo escrito.","Búsquedas más rápidas y más conversión."]],
 transformer:[0,["","E-commerce internacional","Traducir automáticamente miles de fichas de producto a 5 idiomas.","Modelo de traducción con revisión humana de muestras.","Lanzamiento en nuevos países en semanas, no meses."]],
 autoenc:[0,["","Industria","Detectar piezas defectuosas en imágenes sin ejemplos de defectos.","Autoencoder entrenado solo con piezas buenas: las malas se reconstruyen mal.","Inspección automática desde el primer día de producción."]],
 som:[0,["","Energía","Perfiles de consumo diario de miles de contadores inteligentes.","Mapa donde perfiles de consumo parecidos quedan juntos.","Tarifas por perfil de consumo."]],
 kmeans:[0,["","Telecomunicaciones","Agrupar antenas por patrón de tráfico horario.","Grupos de antenas «residenciales», «oficinas», «ocio».","Mantenimiento programado en las horas de menos uso de cada grupo."]],
 kmedoids:[0,["","Educación","Elegir 5 alumnos representativos para entrevistas en profundidad.","Los medoides son alumnos reales que representan a cada perfil.","Entrevistas que cubren todos los perfiles con pocas personas."]],
 jerarquico:[0,["","Biología","Agrupar especies o muestras por similitud genética.","El dendrograma muestra el árbol de parecidos a cualquier nivel.","Clasificación en familias y subfamilias."]],
 dbscan:[0,["","Seguros agrarios","Detectar zonas afectadas por granizo a partir de partes geolocalizados.","Grupos de partes densos = zonas afectadas; partes sueltos = ruido.","Peritaje por zonas en vez de parte a parte."]],
 gmm:[0,["","Retail","Clientes que compran tanto en tienda como online en distinta proporción.","Pertenencia blanda a «tienda» y «online».","Comunicaciones omnicanal ajustadas a la mezcla de cada cliente."]],
 pca:[0,["","Calidad","Vigilar 50 variables de proceso con un único gráfico de control.","Los primeros componentes resumen el estado del proceso.","Detección de desviaciones con un gráfico en vez de 50."]],
 tsne:[0,["","Producto","Revisar si los tickets de soporte se agrupan por tema.","Mapa 2D de embeddings de tickets para inspección visual.","Detectar temas mezclados en las categorías actuales."]],
 umap:[0,["","Música","Mapa de canciones del catálogo según su audio.","Proyección de embeddings de audio a un mapa navegable.","Listas de reproducción por «zonas» del mapa."]],
 iforest:[0,["","Compras","Facturas de proveedores con importes o frecuencias raras.","Rareza por proveedor, importe, día y aprobador.","Auditoría centrada en las facturas más extrañas."]],
 lof:[0,["","Movilidad","Trayectos con tarifas raras para su zona y hora.","Cada trayecto se compara con los de su vecindario.","Detección de cobros indebidos."]],
 apriori:[0,["","Software","Qué funcionalidades usan juntas los clientes de un SaaS.","Reglas «usa informes → usa exportar a Excel».","Paquetes de producto y onboarding guiado."]],
 reco:[0,["","Delivery","Qué restaurante recomendar a cada usuario.","Factores latentes de gusto a partir de pedidos.","Portada personalizada con más pedidos."]],
 contentbased:[0,["","Portal inmobiliario","Pisos parecidos al que el usuario está viendo.","Similitud por características y descripción del anuncio.","Más contactos con anunciantes por visita."]],
 topic:[0,["","Sector público","¿De qué se quejan los ciudadanos en el buzón municipal?","Temas descubiertos en miles de quejas.","Presupuesto priorizado según los temas más frecuentes."]],
 bayesnet:[0,["","Transporte","¿Por qué se retrasan los trenes: clima, averías u ocupación?","Red con conocimiento de los técnicos y datos de operación.","Inversión en la causa con más impacto."]],
 hmm:[0,["","Voz","Reconocer fonemas en una grabación (uso clásico de los HMM).","Estados ocultos = sonidos; observaciones = características del audio.","Base histórica de los sistemas de dictado."]],
 arima:[0,["","Hostelería","Reservas diarias de un hotel urbano sin estacionalidad marcada.","Previsión a corto plazo con intervalos.","Ajuste de tarifas para los próximos 14 días."]],
 sarima:[0,["","Ocio","Visitantes mensuales de un parque temático.","Estacionalidad anual (verano y puentes) capturada en el modelo.","Contratación y apertura de atracciones por temporada."]],
 sarimax:[1,["","Movilidad urbana","Uso diario de bicicletas compartidas según lluvia y temperatura previstas.","La previsión meteorológica entra como exógena.","Redistribución de bicis antes del pico de demanda."]],
 prophet:[0,["","Cines","Entradas diarias con estrenos, festivos y vacaciones escolares.","Estrenos y vacaciones como eventos y regresores.","Personal de taquilla y bar ajustado a cada día."]],
 hw:[0,["","Gasolineras","Litros vendidos por estación de servicio y semana.","Suavizado de nivel, tendencia y estacionalidad por estación.","Pedidos al proveedor sin quedarse sin combustible."]],
 bandit:[0,["","Pricing","Probar tres precios de lanzamiento de un producto digital.","El bandit desplaza tráfico hacia el precio con más ingreso por visita.","Precio elegido perdiendo menos ingresos durante la prueba."]],
 qlearning:[0,["","Videojuegos","Personaje controlado por IA en un juego de tablero sencillo.","Tabla de valores aprendida jugando contra sí mismo.","Rival con distintos niveles de dificultad."]],
 sarsa:[0,["","Cobros","Qué acción de recobro aplicar cada semana sin quemar la relación con el cliente.","Política que tiene en cuenta el coste de probar acciones agresivas.","Más recobro con menos quejas."]],
 dqn:[0,["","Almacenes","Robot que decide qué estantería traer primero.","Red que estima el valor de cada acción en un estado complejo del almacén.","Más pedidos preparados por hora en simulación."]],
 ppo:[0,["","Edificios","Control de climatización de un edificio de oficinas.","Política continua (potencia de cada planta) aprendida en un simulador.","Menos consumo manteniendo el confort."]],
 automl:[0,["","E-commerce","Elegir rápidamente el mejor modelo de previsión de devoluciones.","Ranking de modelos y variables más útiles.","Política de devoluciones informada en una semana."]],
 pyspark:[0,["","Analítica web","Procesar los logs de navegación de todo un año.","Agregaciones por sesión y usuario distribuidas.","Embudo de conversión completo, no muestreado."]]
};
Object.keys(N).forEach(function(id){ if(CASOS[id]) CASOS[id][N[id][0]] = N[id][1]; });
})();
